(defun fload (filename)
  (let* ((dot-string (make-string (cl:- 40 (cl:+ 3 (length filename)))
				  :initial-element #\.)))
    (format t "Loading ~a ..." filename)
    (load filename)
    (format t "~a OK~%" dot-string)))
(fload "src/gagm.lisp")
(fload "src/package.lisp")
(fload "src/utilities.lisp")
(fload "src/macros.lisp")
(fload "src/ast-nodes.lisp")
(fload "src/writer-html.lisp")
(fload "src/writer-latex.lisp")
